apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: productpage
spec:
  protocol: http
  maxInboundConnections: 1
  upstreamConfig:
    defaults:
      limits: 
        maxConnections: 1
        maxPendingRequests: 1
        maxConcurrentRequests: 1
      passiveHealthCheck: 
        interval: 1s
        maxFailures: 1
        enforcingConsecutive5xx: 100